### ISSUE TITLE
[Meta] - Continue MailExtension conversion

### ISSUE THREAD

**Issue by dugite-code** [TB-throwback/LookOut-fix-version#53]
# Experiment wrapper API [Currently used]

The experiment wrapper won't be supported forever and should be eventually removed

TB68.x Branch: https://github.com/TB-throwback/LookOut-fix-version/tree/Experiment-wrapper-API
TB78.x Branch: https://github.com/TB-throwback/LookOut-fix-version/tree/Experiment-wrapper-API_78

## Making current work tb78 compatible

https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-Finalizing

https://developer.thunderbird.net/add-ons/updating/tb78/changes

---

# Future webextension works?

* https://thunderbird-webextensions.readthedocs.io/en/latest/index.html

Possible order of fetching attachments?
1. Event [onMessageDisplayed(tabId, message)](https://thunderbird-webextensions.readthedocs.io/en/lates/messageDisplay.html#onmessagedisplayed-tabid-message)
2. [MessageHeader[id]](https://thunderbird-webextensions.readthedocs.io/en/latest/messages.html#messages-messageheader)
3. [messageparts](https://thunderbird-webextensions.readthedocs.io/en/latest/messages.html#messagepart) or [getfull-messageid](https://thunderbird-webextensions.readthedocs.io/en/latest/messages.html#getfull-messageid)

One issue that needs to be worked out is the messageid. The ID returned in the Message Header isn't the messageid.

Updating attachment will probably require a webextension experiment
* https://webextensions-experiments.readthedocs.io/en/latest/

**Edit:** Hopefully TNEF support will finnaly be integrated directly into thunderbird
http://lists.thunderbird.net/pipermail/maildev_lists.thunderbird.net/2019-November/002024.html

>       Investigate Microsoft TNEF support  [TB78/TB2021]
>
>Investigate if integrating TNEF support can be integrated cleanly 
enough. If it can, we could integrate it. If not, we should take the 
needed steps to make it possible.
>
>
>Tracked in bug 77811 <https://bugzilla.mozilla.org/show_bug.cgi?id=77811>.

**Edit 2:** It has been added to an official roadmap
https://developer.thunderbird.net/planning/roadmap#investigate-microsoft-tnef-support-tb-78-tb-2021

**Comment by jobisoft** [comment]
Hi,

Thunderbird has created a new staff position called "Add-on support engineer" - which happens to be me (John Bieling). In the last weeks I have worked on a shurtcut update path, to get legacy extensions working in TB78 again, with the minimal amount of work possible. It is using an Experiment wrapper API:
https://github.com/thundernest/addon-developer-support/wiki

After the initial update, we can remove the legacy parts step by step. The idea is to get the add-on compatible as easy and as fast as possible and do the "full" conversion to a true MailExtension without Experiements APIs in smaller steps, while your users can already use your add-on in TB78.

I would love to see your add-on in TB78 and I offer help via our community channels:
https://developer.thunderbird.net/add-ons/community

**Comment by dugite-code** [comment]
Well this looks promising. I'm hoping to finally have some free time to return to doing some Open source work so your efforts here couldn't come at a better time

**Comment by jobisoft** [comment]
Ping me, if you need any help.

**Comment by jobisoft** [comment]
You probably have to change this line:
https://github.com/TB-throwback/LookOut-fix-version/commit/4d68b3443d268859f376ad95208a3b58ab4521a9#diff-540d11b9917979031405b9f20f03a2d0R13
to 

window.glookout.loadSettings(false);

The onLoad and onUnload functions of the injection script are not running in the window scope. As you load your scripts into the window scope (which is fine) you need to include the window. prefix inside of these two functions to reach your code. The injected XUL will run in window scope, so no changes required there.

**Comment by dxgldotorg** [comment]
Thunderbird 78 just dropped on my system, and now I can no longer view my employer's pay stubs.

**Comment by dugite-code** [comment]
@dxgldotorg I'm unsure when the porting will be done as I'm quite a bit out of my depth with web extensions and the original code wasn't written with them in mind.

**Comment by dugite-code** [comment]
# Not to be used in production:

- [x] Generic files decode
- [x] Options menu is working as expected
- [ ] Event handling is untested

[Alpha release: v3.0.00a1](https://github.com/TB-throwback/LookOut-fix-version/releases/tag/v3.0.00a1)

**Comment by dxgldotorg** [comment]
Just put it on my Thunderbird, I can once again decode my employer's Outlook attachments.

**Comment by jobisoft** [comment]
@dugite-code : I there a specific roadblock, I could try to look at?

**Comment by dugite-code** [comment]
Not really, The big hold-up is I just haven't had any time to dig into my old archive and test the event handling. I plan to get to that this week

**Comment by dugite-code** [comment]
Version 3.0.1 Has been uploaded to ATN and is pending review.

**Comment by jobisoft** [comment]
*tada*
https://addons.thunderbird.net/de/thunderbird/addon/lookout-fix-version/

Thanks for your efforts!
